package com.example.successmeter.data.local.db.dao

// Room annotations for DAO, queries, insert, update.
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
// Our Room entity for goals.
import com.example.successmeter.data.local.db.entity.GoalEntity
// Kotlin Flow so UI can react to DB changes.
import kotlinx.coroutines.flow.Flow

/**
 * DAO (Data Access Object) for GoalEntity.
 *
 * Responsibility:
 * - Define HOW we read/write goals in SQLite (SQL statements).
 * - Expose a clean Kotlin API (Flows + suspend functions).
 *
 * It should NOT:
 * - Know anything about ViewModels, UI, or use cases.
 * - Contain business rules (like "targetDate must be in the future").
 */
@Dao
interface GoalDao {

    /**
     * Observe ALL non-archived goals in the DB.
     * Returns:
     * - Flow<List<GoalEntity>>
     *   - Flow: stream that emits whenever the underlying table changes.
     *   - List<GoalEntity>: a snapshot of all current rows.
     * Usage:
     * - Probably more for debugging or generic screens.
     * - For the Goals tree we’ll more often use observeGoalsForChiefAim().
     */
    @Query("SELECT * FROM goals WHERE isArchived = 0")
    fun observeAllGoals(): Flow<List<GoalEntity>>



    /**
     * Observe all non-archived goals for a single chief aim.
     *
     * This is the main query used by the Goals tree feature:
     * - GoalsRepository will call this.
     * - Use case will build a tree from the flat list.
     */
    @Query(
        """
        SELECT * FROM goals
        WHERE chiefAimId = :chiefAimId
          AND isArchived = 0
        """
    )
    fun observeGoalsForChiefAim(
        chiefAimId: Long,
    ): Flow<List<GoalEntity>>


    /**
     * Insert or update a goal.
     *
     * OnConflictStrategy.REPLACE:
     * - If a row with the same primary key (id) exists, it will be replaced.
     * - This is a simple upsert pattern for now.
     *
     * Return value:
     * - Long = rowId (primary key). For autoGenerated ids, this gives us the new id.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsertGoal(entity: GoalEntity): Long


    /**
     * Update a goal without changing the primary key.
     *
     * This is useful when:
     * - You loaded a GoalEntity from DB,
     * - Modified some fields in Kotlin,
     * - And now want to push those changes back.
     *
     * Note:
     * - Room matches rows by primary key (id).
     */
    @Update
    suspend fun updateGoal(entity: GoalEntity)


    @Query(
        """
        UPDATE goals
        SET isCompleted = 1,
            completedAt = :completedAt
        WHERE id = :goalId
        """
    ) suspend fun markGoalCompleted(
        goalId: Long,
        completedAt: Long,
    )


    @Query(
        """
        UPDATE goals
        SET isArchived = 1
        WHERE id = :goalId
        """
    ) suspend fun archiveGoal(
        goalId: Long,
    )
}
